import React from "react";
import Link from "next/link";
import { getPublicSettings } from "@/lib/public-api";
import { Footer } from "@/components/public/Footer";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Terms & Conditions — MAYA Design & Build",
  description: "Commercial, estimation, and engineering terms for MAYA Design & Build.",
};


export default async function TermsPage() {
  const settings = await getPublicSettings();
  const rawTerms = settings.terms_and_conditions || "";

  return (
    <div className="min-h-screen bg-[#0D0F12] text-[#F4F4F6] flex flex-col justify-between selection:bg-[#C5A869]/30 selection:text-white">
      {/* Header Bar */}
      <header className="border-b border-[#2B313D] bg-[#0D0F12]/80 backdrop-blur-md sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
          <Link href="/" className="inline-block group">
            <span className="text-xl sm:text-2xl font-black tracking-[0.2em] text-[#C5A869]">
              MAYA
            </span>
            <span className="text-[10px] uppercase tracking-[0.25em] text-neutral-400 block font-medium">
              Design &amp; Build
            </span>
          </Link>

          <Link
            href="/"
            className="text-xs font-mono uppercase tracking-wider text-neutral-400 hover:text-[#C5A869] transition"
          >
            &larr; Back to Home
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 flex-1 w-full space-y-8">
        <div className="space-y-3 pb-6 border-b border-[#2B313D]">
          <span className="text-xs font-mono uppercase tracking-widest text-[#C5A869] font-bold">
            Legal &amp; Engineering Agreement
          </span>
          <h1 className="text-3xl sm:text-4xl font-black text-white tracking-tight">
            Terms &amp; Conditions
          </h1>
          <p className="text-xs text-neutral-400 font-mono">
            Last Updated: 2026 • Commercial &amp; Professional Standards
          </p>
        </div>

        <div className="prose prose-invert max-w-none text-neutral-300 leading-relaxed space-y-6 text-sm">
          {rawTerms ? (
            <div className="whitespace-pre-wrap">{rawTerms}</div>
          ) : (
            <div className="space-y-4">
              <p>
                Welcome to <strong>MAYA Design &amp; Build</strong>. By accessing our website,
                using our dynamic quotation calculator, or submitting consultation requests, you
                agree to the terms described below.
              </p>
              <h3 className="text-lg font-bold text-white mt-6">1. Commercial Estimates</h3>
              <p>
                All estimates, line-item pricing, and tentative figures generated by the website
                calculator are indicative engineering guidelines. Final binding commercial terms,
                scopes of work, and bills of quantities (BOQ) are subject to physical site inspection
                and execution of a formal contract.
              </p>
              <h3 className="text-lg font-bold text-white mt-6">2. Intellectual Property</h3>
              <p>
                All 3D architectural visualizations, photographs, blueprints, elevations, and
                design concepts featured on this website are the intellectual property of MAYA Design
                &amp; Build and its respective clients.
              </p>
              <h3 className="text-lg font-bold text-white mt-6">3. Professional Supervision</h3>
              <p>
                Engineering supervision and turnkey execution are governed strictly by applicable
                Indian building codes and local municipal safety regulations.
              </p>
            </div>
          )}
        </div>
      </main>

      <Footer settings={settings} />
    </div>
  );
}
