import React from "react";
import { getPublicSettings } from "@/lib/public-api";
import { Navbar } from "@/components/public/Navbar";
import { Footer } from "@/components/public/Footer";
import { FloatingCallButton } from "@/components/public/FloatingCallButton";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Terms & Conditions — MAYA Design & Build",
  description: "Commercial, estimation, and engineering terms for MAYA Design & Build.",
};

export default async function TermsPage() {
  const settings = await getPublicSettings();
  const rawTerms = settings.terms_and_conditions || "";

  return (
    <div className="min-h-screen bg-[#F9F6F5] text-[#032D47] font-sans flex flex-col justify-between selection:bg-[#E1A857] selection:text-[#032D47]">
      {/* Unified Public Navbar */}
      <Navbar />

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-36 pb-20 flex-1 w-full space-y-10">
        <div className="space-y-3 pb-6 border-b border-[#BCC1C4]/40">
          <span className="text-xs font-mono uppercase tracking-widest text-[#966015] font-bold">
            Legal &amp; Engineering Agreement
          </span>
          <h1 className="text-3xl sm:text-5xl font-black text-[#032D47] tracking-tight">
            Terms &amp; Conditions
          </h1>
          <p className="text-xs text-[#455668] font-mono">
            Commercial &amp; Professional Standards • MAYA Design &amp; Build
          </p>
        </div>

        <div className="bg-[#FFFFFF] border border-[#BCC1C4]/60 p-8 sm:p-12 rounded-xs shadow-xs text-[#455668] leading-relaxed space-y-6 text-sm sm:text-base">
          {rawTerms ? (
            <div className="whitespace-pre-wrap">{rawTerms}</div>
          ) : (
            <div className="space-y-5">
              <p>
                Welcome to <strong className="text-[#032D47]">MAYA Design &amp; Build</strong>. By accessing our website,
                using our dynamic quotation calculator, or submitting consultation requests, you
                agree to the terms described below.
              </p>
              <h3 className="text-lg font-black text-[#032D47] mt-8 pt-4 border-t border-[#BCC1C4]/30">1. Commercial Estimates</h3>
              <p>
                All estimates, line-item pricing, and tentative figures generated by the website
                calculator are indicative engineering guidelines. Final binding commercial terms,
                scopes of work, and bills of quantities (BOQ) are subject to physical site inspection
                and execution of a formal contract.
              </p>
              <h3 className="text-lg font-black text-[#032D47] mt-8 pt-4 border-t border-[#BCC1C4]/30">2. Intellectual Property</h3>
              <p>
                All 3D architectural visualizations, photographs, blueprints, elevations, and
                design concepts featured on this website are the intellectual property of MAYA Design
                &amp; Build and its respective clients.
              </p>
              <h3 className="text-lg font-black text-[#032D47] mt-8 pt-4 border-t border-[#BCC1C4]/30">3. Professional Supervision</h3>
              <p>
                Engineering supervision and turnkey execution are governed strictly by applicable
                Indian building codes (IS standards) and local municipal safety regulations.
              </p>
            </div>
          )}
        </div>
      </main>

      <Footer settings={settings} />

      {/* Floating Call Action Button */}
      <FloatingCallButton phone={settings.contact_phone} />
    </div>
  );
}
